.test: &test
  stage: test
  before_script:
    - ./script/bootstrap
  script:
    - ./script/cibuild

test 3.0:
  image: "ruby:3.0"
  <<: *test

test 3.1:
  image: "ruby:3.1"
  <<: *test

test 3.2:
  image: "ruby:3.2"
  <<: *test

test 3.3:
  image: "ruby:3.3-rc"
  <<: *test
