image: "ruby:3.0-alpine"

cache:
  paths:
    - vendor/ruby
  key: ruby-3.0

before_script:
  - apk add --update git
  - gem install bundler
  - bundle install --path vendor/ruby

rubocop:
  script:
    - bundle exec rubocop

rspec:
  script:
    - bundle exec rspec spec
