---
SHA256:
  metadata.gz: 4e9ba53d88e7d7525346e2f989314a18774ceb1838474216079f6bd27622f6a3
  data.tar.gz: da98ab64b2cce6b0878d84a2eb8a94dfe2dd47b9141a32d6240b03ca0adf44c6
SHA512:
  metadata.gz: '09f6ae0b068b11c3778f83f082b07d2a22867ef7b4af5b94a3bcf71ff4b44f8ddd16d7f224c0063f112332cd670bdc375a774c8e587095dd339c3bf069f147f8'
  data.tar.gz: 5de9909cfa5f4a73947f75e18be254e5c53030fb1ccf402ce2773aabb101a441a1da30091afe355c0f30d4a21d345ff15a07723008bc996ff452e995c3b73e42
