.default:
  image: "ruby:${RUBY_VERSION}"
  before_script:
    - ruby -v
    - which ruby
    - gem install bundler
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

rspec:
  extends:
    - .default
  stage: test
  script:
    - bundle exec rspec
  parallel:
    matrix:
      - RUBY_VERSION: ['2.7', '3.0', '3.1', '3.2']
