name: Lint
on:
  - push

jobs:
  style-check:
    name: Style check
    runs-on: ubuntu-24.04
    container:
      image: ruby:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bundle
        run: bundle install

      - name: Run Rubocop
        run: bundle exec rubocop -D

  type-check:
    name: Type check
    runs-on: ubuntu-24.04
    container:
      image: ruby:3.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bundle
        run: bundle install

      - name: Run Steep
        run: bundle exec rake steep:check
