name: Package
on:
  - push

jobs:
  test-rake-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ruby: ["3.3"]
        arch: [amd64, arm64]
        libc: [gnu]
        include:
          - arch: amd64
            platform: x86_64-linux
          - arch: arm64
            platform: aarch64-linux

    name: Test build without fetching libddwaf (Ruby ${{ matrix.ruby }}, ${{ matrix.arch }}, ${{ matrix.libc }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        id: build-image
        uses: ./.github/actions/docker-build-ruby
        with:
          ruby-version: ${{ matrix.ruby }}
          arch: ${{ matrix.arch }}
          libc: ${{ matrix.libc }}

      - name: Bundle install
        run: ${{ steps.build-image.outputs.run-cmd }} bundle install

      - name: Build gem
        run: ${{ steps.build-image.outputs.run-cmd }} bundle exec rake build

      - name: List artifact files
        run: find .
        working-directory: pkg

      - name: Install gem
        run: ${{ steps.build-image.outputs.run-cmd }} gem install --verbose pkg/*.gem

      - name: Run smoke test
        run: ${{ steps.build-image.outputs.run-cmd }} ruby -e 'begin require "libddwaf"; rescue LoadError => e; puts e.message; else fail "loaded when it should not"; end'

  test-rake-binary:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        ruby: ["3.3", "9.4"]
        arch: [amd64, arm64]
        libc: [gnu, musl]
        include:
          - arch: amd64
            platform: x86_64-linux:llvm
          - arch: arm64
            platform: aarch64-linux:llvm
          - ruby: 3.3
            jruby: false
          - ruby: 9.4
            jruby: true
        exclude:
          - ruby: 9.4
            libc: musl

    name: Test gem build (${{ matrix.jruby == true && 'Jruby' || 'Ruby'}} ${{ matrix.ruby }}, ${{ matrix.arch }}, ${{ matrix.libc }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build docker image
        id: build-image
        uses: ./.github/actions/docker-build-ruby
        with:
          ruby-version: ${{ matrix.ruby }}
          arch: ${{ matrix.arch }}
          libc: ${{ matrix.libc }}
          jruby: ${{ matrix.jruby }}

      - name: Bundle install
        run: ${{ steps.build-image.outputs.run-cmd }} bundle install

      - name: Build binary gem
        run: ${{ steps.build-image.outputs.run-cmd }} bundle exec rake binary[${{ matrix.platform }}]

      - name: List artifact files
        run: find .
        working-directory: pkg

      - name: Install gem
        run: ${{ steps.build-image.outputs.run-cmd }} gem install --verbose pkg/*.gem

      - name: Run smoke test
        run: ${{ steps.build-image.outputs.run-cmd }} ruby -r 'libddwaf' -e 'p Datadog::AppSec::WAF::LibDDWAF.ddwaf_get_version'

  test-rake-binary-on-darwin:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, macos-15-large]
        include:
          - os: macos-15
            platform: arm64-darwin
          - os: macos-15-large
            platform: x86_64-darwin

    name: Test gem build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Bundle
        run: bundle install

      - name: Build binary gem
        run: bundle exec rake binary[${{ matrix.platform }}]

      - name: Install gem
        run: gem install --verbose pkg/*.gem

      - name: Run smoke test
        run: ruby -r 'libddwaf' -e 'p Datadog::AppSec::WAF::LibDDWAF.ddwaf_get_version'
