---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authenticator-deployment
  labels:
    app: authenticator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authenticator
  template:
    metadata:
      labels:
        app: authenticator
    spec:
      imagePullSecrets:
        - name: gitlab-registry
      containers:
        - name: authenticator
          image: registry.gitlab.com/gitlab-org/modelops/applied-ml/review-recommender/authenticator:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          args: []
          env:
            - name: AUTHENTICATOR_SERVICE_PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: authenticator-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: authenticator
