---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-deployment
  labels:
    app: pubsub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pubsub
  template:
    metadata:
      labels:
        app: pubsub
    spec:
      containers:
        - name: pubsub
          image: singularities/pubsub-emulator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PUBSUB_PROJECT_ID
              value: project-test
            - name: PUBSUB_LISTEN_ADDRESS
              value: 0.0.0.0:8432

---
apiVersion: v1
kind: Service
metadata:
  name: pubsub
  labels:
    app: pubsub
spec:
  type: ClusterIP
  selector:
    app: pubsub
  ports:
    - port: 8432
      targetPort: 8432
