products:
 default: 'products/'
 mine: 'products/mine/'
 search: 'products/search/'
report:
  sales:
    default: 'reports/sales/'
    region: 'reports/sales/regions/'
  ads: 'reports/ads/'
ranks:
  default: 'ranks/'
  snapshots: 'ranks/snapshots/'
featured: 'featured/'
reviews:
  default: 'reviews/'
  count: 'reviews/count/'
events: 'events/'
archive: 'archive/'
users: 'users/'
external_accounts: 'external_accounts/'
data:
  categories: 'data/categories/'
  countries: 'data/countries/'
  languages: 'data/languages/'
  currencies: 'data/currencies/'
  stores: 'data/stores/'
usage: 'usage/'