---
SHA256:
  metadata.gz: b613ee573cfdb45f463ec2456e9f1f6d4c0e6f67c6b205212f14ed0dc4dbb06e
  data.tar.gz: bcfc09e32ffed628167006fa15982ec389a77236b828ffa4def2f5bc97ac2999
SHA512:
  metadata.gz: 419d18f1f7b514430b1b06271e450c44062d37b84793d1c329ee19601ba8f7b6a392903ab04f7a08ea4ae400d4709e4c6eef99ba2637650a7cbbf7f4a0126d27
  data.tar.gz: abad7e30a864b5bc327ed2b37c3552140b43a46064cbd6292bec092343b2c9609c842cd87e194744d6f3a7012e2c792ec1d6488b10c7a1f603dbcc517e018f3e
