---
SHA256:
  metadata.gz: 8c96004a65d9260bcb2b2605f83092660d19c1d4690b2b2a0327f53dc0c748d0
  data.tar.gz: 65154dd4b7ca712e41990a966882da537bf08c622e5ebc7e18d689c66baab0f5
SHA512:
  metadata.gz: d30ea5b2821344e3c68a07e1d1a18fede760e705e167338192fe544440a16fd5c630c9d3e48889c45996d6c0d85459c13761acab3c6f86a35550165fef31747b
  data.tar.gz: 7e413abf01e1e805028bcd1e1ef99b71bc5242ae5a26e8b7588c35daf6c7d27ca601f8ea3b0218d858b1ca3bc62890d6b14bbe94b4f69f3e1b580bb0d083eb86
